name: flutter_flutter
description: A new Flutter project.

publish_to:
version: 1.0.0+1

environment:
  sdk: ^3.0.0
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  http: ^1.1.0
  dio: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  font_awesome_flutter: ^10.5.0
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.1
  dio: ^5.3.2



flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200

